name: pipeline-ecr-ebs
on:
  push:
    branches: [ main ]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  MODULE_NAME: ${{ vars.MODULE_NAME }}
  TAG: latest
  STACK_NAME: "64bit Amazon Linux 2 v3.5.7 running Docker"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODULE_FULLNAME: ${{ vars.PROJECT_NAME }}/${{ vars.MODULE_NAME }}
      REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
    steps:
      # ... seus passos de build aqui ...

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4

      - name: ebconfig
        run: |
          sed -i='' "s/\$AWS_ACCOUNT_ID/${{ secrets.AWS_ACCOUNT_ID }}/" Dockerrun.aws.json
          sed -i='' "s/\$PROJECT_NAME/${{ vars.PROJECT_NAME }}/" Dockerrun.aws.json
          sed -i='' "s/\$MODULE_NAME/${{ vars.MODULE_NAME }}/" Dockerrun.aws.json
          sed -i='' "s/\$TAG/${{ env.TAG }}/" Dockerrun.aws.json

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install pip and awsebcli
        run: |
          sudo wget https://bootstrap.pypa.io/get-pip.py
          sudo python3 ./get-pip.py
          sudo pip install "pyyaml<5.4"
          sudo pip install --upgrade setuptools
          sudo pip install --upgrade pip awsebcli

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy --verbose



