name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências do backend
        run: npm --prefix backend install

      - name: Executar testes (ignorando service.spec.ts)
        run: npm --prefix backend test -- --testPathIgnorePatterns=backend/src/products/products.service.spec.ts
